server:
  port: 8000

spring:
  profiles:
    active: local # 디폴트 환경
  messages:
    basename: i18n/exception
    encoding: UTF-8
  social:
    kakao:
      client_id: 623e83defbdfd4eb7c688561568d2a0d # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  jwt:
    secret: govlepel@$;